#!/usr/bin/env node
import { readFile, writeFile } from "node:fs/promises"

const colors = await readFile(import.meta.dirname + "/colors.txt", "utf8")

const variables = []
for (const line of colors.split("\n")) {
  if (!line.trim()) continue
  const [variable] = line.trim().split(":")
  const name = variable!.trim().substring(2)
  variables.push(`--color-${name}: var(--${name});`)
}

const output = `
/* Generated by script/tailwind.ts */
/* Do not edit this file manually */

@theme {
  --color-*: initial;
  ${variables.join("\n  ")}
}
`

await writeFile(import.meta.dirname + "/../src/styles/tailwind/colors.css", output.trim())
