import { describe, expect, test } from "bun:test"
import { SqliteClient } from "@effect/sql-sqlite-bun"
import type { EffectDrizzleSqlite } from "@opencode-ai/effect-drizzle-sqlite"
import { EffectDrizzleSqlite as EffectDrizzleSqliteValue } from "@opencode-ai/effect-drizzle-sqlite"
import { Effect, Layer } from "effect"
import { sql } from "drizzle-orm"
import {
  layer as capabilityLayer,
  Service as CapabilityService,
  WorkspaceMembershipService as CapabilityMembership,
} from "@opencode-ai/core/capability/service"
import { Database } from "@opencode-ai/core/database/database"
import { DatabaseMigration } from "@opencode-ai/core/database/migration"
import capsuleMigration from "@opencode-ai/core/database/migration/20260821_capsule"
import {
  DefaultInteractiveContextBudget,
  layer,
  Service,
  type ContextCapsuleStore,
  type StoredCapsule,
} from "@opencode-ai/core/context-broker/capsule"

const SENTINEL = "CTXPACK_SECRET_SENTINEL_7812"

const makeDb = EffectDrizzleSqliteValue.makeWithDefaults()
type Db = EffectDrizzleSqlite.EffectSQLiteDatabase

interface StoreContext {
  store: ContextCapsuleStore
  db: Db
}

// Fresh :memory: database + the capsule migration. DatabaseMigration.apply is
// not used on the empty DB because schema.gen is regenerated by M1 (central
// integration action); applyOnly runs this lane's raw SQL migration directly.
const withStore = <A>(f: (ctx: StoreContext) => Promise<A>) =>
  Effect.runPromise(
    Effect.gen(function* () {
      const db = yield* makeDb
      yield* DatabaseMigration.applyOnly(db, [capsuleMigration])
      const store = yield* Service.pipe(
        Effect.provide(Layer.provide(layer, Layer.succeed(Database.Service, { db }))),
      )
      return yield* Effect.promise(() => f({ store, db }))
    }).pipe(Effect.provide(SqliteClient.layer({ filename: ":memory:", disableWAL: true })), Effect.scoped),
  )

const ROOMY_BUDGET = { ...DefaultInteractiveContextBudget, maximumBytes: 1_000_000_000, maximumEstimatedTokens: 1_000_000_000 }

const makeCapsule = (overrides: Partial<StoredCapsule> = {}): StoredCapsule => ({
  id: "",
  version: 1,
  workspaceId: "wrk_1",
  purpose: "ctxpack context",
  audience: ["ctxpack"],
  summary: "A summary of the workspace context.",
  facts: [{ fact: "the sky is blue" }],
  references: [
    { ref: { type: "ctxpack-fragment", id: "ref_1" }, label: "one" },
    { ref: { type: "ctxpack-fragment", id: "ref_2" }, label: "two" },
    { plain: "always-kept" },
  ],
  artifactRefs: [{ ref: { type: "ctxpack-artifact", id: "art_1" } }],
  recentEvents: [{ event: "hello" }],
  contentHash: "hash-abc-123",
  createdAt: Date.now(),
  expiresAt: undefined,
  createdBy: { userId: "user-1", instanceId: "inst_1", operationId: "op_1" },
  budget: DefaultInteractiveContextBudget,
  ...overrides,
})

describe("ContextCapsuleStore", () => {
  test("store/get round trip preserves createdBy, budget, and references", async () => {
    await withStore(async ({ store }) => {
      const stored = await Effect.runPromise(store.store(makeCapsule()))
      expect(stored.id.startsWith("ctxkpsl_")).toBe(true)
      const loaded = await Effect.runPromise(store.get("wrk_1", stored.id))
      expect(loaded).toEqual(stored)
      expect(loaded!.createdBy).toEqual({ userId: "user-1", instanceId: "inst_1", operationId: "op_1" })
      expect(loaded!.budget).toEqual(DefaultInteractiveContextBudget)
      expect(loaded!.references).toHaveLength(3)
      expect(loaded!.summary).toBe("A summary of the workspace context.")
    })
  })

  test("store assigns an id when empty; re-store with the same id is an immutable-write conflict", async () => {
    await withStore(async ({ store }) => {
      const stored = await Effect.runPromise(store.store(makeCapsule()))
      expect(stored.id).toMatch(/^ctxkpsl_/)

      await expect(
        Effect.runPromise(store.store({ ...makeCapsule(), id: stored.id })),
      ).rejects.toMatchObject({ _tag: "ContextCapsule.Conflict", capsuleID: stored.id })
    })
  })

  test("get with the wrong workspace returns undefined", async () => {
    await withStore(async ({ store }) => {
      const stored = await Effect.runPromise(store.store(makeCapsule()))
      const loaded = await Effect.runPromise(store.get("wrk_other", stored.id))
      expect(loaded).toBeUndefined()
    })
  })

  test("materialize with no requestedRefs returns all references plus byte/token counts", async () => {
    await withStore(async ({ store }) => {
      const stored = await Effect.runPromise(store.store(makeCapsule()))
      const result = await Effect.runPromise(
        store.materialize({ workspaceID: "wrk_1", capsuleID: stored.id, requestedRefs: [], budget: ROOMY_BUDGET }),
      )
      expect(result.status).toBe("ok")
      if (result.status !== "ok") return
      expect(result.content.facts).toEqual([{ fact: "the sky is blue" }])
      expect(result.content.references).toHaveLength(3)
      expect(result.content.artifactRefs).toHaveLength(1)
      expect(result.unresolvedRefs).toEqual([])
      const expectedBytes = new TextEncoder().encode(JSON.stringify(result.content)).length
      expect(result.byteLength).toBe(expectedBytes)
      expect(result.estimatedTokens).toBe(Math.ceil(expectedBytes / 4))
    })
  })

  test("materialize filters by requestedRefs and reports unknown ids as unresolved", async () => {
    await withStore(async ({ store }) => {
      const stored = await Effect.runPromise(store.store(makeCapsule()))
      const result = await Effect.runPromise(
        store.materialize({
          workspaceID: "wrk_1",
          capsuleID: stored.id,
          requestedRefs: ["ref_1", "ref_9"],
          budget: ROOMY_BUDGET,
        }),
      )
      expect(result.status).toBe("ok")
      if (result.status !== "ok") return
      expect(result.content.references.map((ref) => (ref as { ref?: { id?: string } })?.ref?.id)).toEqual([
        "ref_1",
        undefined,
      ])
      expect(result.content.artifactRefs).toEqual([])
      expect(result.unresolvedRefs).toEqual(["ref_9"])
    })
  })

  test("materialize on an expired capsule returns expired", async () => {
    await withStore(async ({ store }) => {
      const stored = await Effect.runPromise(
        store.store(makeCapsule({ expiresAt: Date.now() - 60_000 })),
      )
      const result = await Effect.runPromise(
        store.materialize({ workspaceID: "wrk_1", capsuleID: stored.id, requestedRefs: [], budget: ROOMY_BUDGET }),
      )
      expect(result).toMatchObject({ status: "expired" })
      if (result.status === "expired") expect(result.expiresAt).toBeLessThanOrEqual(Date.now())
    })
  })

  test("materialize reports over-budget for both byte and token limits", async () => {
    await withStore(async ({ store }) => {
      const stored = await Effect.runPromise(store.store(makeCapsule()))
      const tinyBytes = await Effect.runPromise(
        store.materialize({
          workspaceID: "wrk_1",
          capsuleID: stored.id,
          requestedRefs: [],
          budget: { ...DefaultInteractiveContextBudget, maximumBytes: 4, maximumEstimatedTokens: 1_000_000 },
        }),
      )
      expect(tinyBytes).toMatchObject({ status: "over-budget", limit: "bytes", maximum: 4 })
      if (tinyBytes.status === "over-budget") expect(tinyBytes.current).toBeGreaterThan(4)

      const tinyTokens = await Effect.runPromise(
        store.materialize({
          workspaceID: "wrk_1",
          capsuleID: stored.id,
          requestedRefs: [],
          budget: { ...DefaultInteractiveContextBudget, maximumBytes: 1_000_000_000, maximumEstimatedTokens: 1 },
        }),
      )
      expect(tinyTokens).toMatchObject({ status: "over-budget", limit: "tokens", maximum: 1 })
      if (tinyTokens.status === "over-budget") expect(tinyTokens.current).toBeGreaterThan(1)
    })
  })

  test("corrupt stored JSON surfaces a typed ContextCapsule.Corrupt error", async () => {
    await withStore(async ({ store, db }) => {
      await Effect.runPromise(
        db.run(sql`
          INSERT INTO context_capsule
            (id, workspace_id, purpose, content_hash, capsule_json, created_by_json, budget_json, created_at, expires_at)
          VALUES ('bad', 'wrk_1', 'p', 'h', ${'{"summary": "' + SENTINEL + '", '}, '{}', '{}', 1, NULL)
        `),
      )
      try {
        await Effect.runPromise(store.get("wrk_1", "bad"))
        expect.unreachable("corrupt row should have failed")
      } catch (error) {
        expect(error).toMatchObject({ _tag: "ContextCapsule.Corrupt", capsuleID: "bad", workspaceID: "wrk_1" })
        expect(String(error)).not.toContain(SENTINEL)
      }
    })
  })

  test("sentinel redaction: content appears only in returned capsules, never in errors", async () => {
    await withStore(async ({ store }) => {
      const stored = await Effect.runPromise(
        store.store(makeCapsule({ summary: SENTINEL })),
      )
      expect(stored.summary).toContain(SENTINEL)

      const loaded = await Effect.runPromise(store.get("wrk_1", stored.id))
      expect(loaded!.summary).toContain(SENTINEL)

      const materialized = await Effect.runPromise(
        store.materialize({ workspaceID: "wrk_1", capsuleID: stored.id, requestedRefs: [], budget: ROOMY_BUDGET }),
      )
      expect(materialized.status).toBe("ok")
      if (materialized.status === "ok") expect(materialized.capsule.summary).toContain(SENTINEL)

      // Immutability conflict: the error carries ids only.
      try {
        await Effect.runPromise(store.store({ ...makeCapsule({ summary: SENTINEL }), id: stored.id }))
        expect.unreachable("re-store should have conflicted")
      } catch (error) {
        expect(error).toMatchObject({ _tag: "ContextCapsule.Conflict" })
        expect(String(error)).not.toContain(SENTINEL)
      }

      // Capability deny never touches capsule content.
      const deny = await Effect.runPromise(
        Effect.provide(
          CapabilityService.pipe(
            Effect.flatMap((service) =>
              service.check({
                userID: "user-9",
                operation: "ctxpack.read",
                subject: { type: "CtxPack", workspaceID: "wrk_1", ctxPackID: stored.id, sensitivity: "public", createdByUserID: "user-1" },
              }),
            ),
          ),
          Layer.provide(
            capabilityLayer,
            Layer.succeed(CapabilityMembership, { isMember: () => Effect.succeed(false) }),
          ),
        ),
      )
      expect(deny).toEqual({ allowed: false, reason: "not-workspace-member" })
      expect(deny.reason).not.toContain(SENTINEL)
    })
  })
})
