import { routes } from "@cybermastery/contracts/routes"

await Bun.write(new URL("../src/generated/routes.ts", import.meta.url),
  `// Generated by script/generate.ts. Do not edit.\nexport const routes = ${JSON.stringify(routes, null, 2)} as const\n`)
