#!/usr/bin/env bun

// Generate the dev-time embedded Web UI module so a source-run
// `opencode serve` serves the freshly built app instead of proxying
// app.opencode.ai. Mirrors createEmbeddedWebUIBundle in script/build.ts, but
// writes the module next to ui.ts (src/server/shared/) where the source
// import resolves. The generated file is gitignored.
//
// Usage: bun run --cwd packages/opencode script/embed-web-ui.ts

import { $ } from "bun"
import path from "path"
import { fileURLToPath } from "url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const dir = path.resolve(__dirname, "..")
process.chdir(dir)

const appDir = path.join(dir, "../app")
const dist = path.join(appDir, "dist")
const channel = process.env.OPENCODE_CHANNEL ?? "dev"
const moduleDir = path.join(dir, "src/server/shared")

console.log("Building Web UI for dev embed…")
await $`OPENCODE_CHANNEL=${channel} bun run --cwd ${appDir} build`

const files = (await Array.fromAsync(new Bun.Glob("**/*").scan({ cwd: dist })))
  .map((file) => file.replaceAll("\\", "/"))
  .filter((file) => !file.endsWith(".map"))
  .sort()

const imports = files.map((file, i) => {
  const spec = path.relative(moduleDir, path.join(dist, file)).replaceAll("\\", "/")
  return `import file_${i} from ${JSON.stringify(spec.startsWith(".") ? spec : `./${spec}`)} with { type: "file" };`
})
const entries = files.map((file, i) => `  ${JSON.stringify(file)}: file_${i},`)
const content = [
  "// @ts-nocheck",
  "// Generated by script/embed-web-ui.ts. Do not edit.",
  "// Dev-only embedded Web UI map; gitignored. Regenerate with: bun run --cwd packages/opencode script/embed-web-ui.ts",
  ...imports,
  "export default {",
  ...entries,
  "}",
  "",
].join("\n")

const target = path.join(moduleDir, "opencode-web-ui.gen.ts")
await Bun.write(target, content)
console.log(`wrote ${path.relative(dir, target)} (${files.length} files)`)
