// Generated by @opencode-ai/httpapi-codegen. Do not edit.
import { Effect, Stream, Schema } from "effect"
import { Sse } from "effect/unstable/encoding"
import { HttpClientError } from "effect/unstable/http"
import { HttpApiClient } from "effect/unstable/httpapi"
import { ClientApi } from "../contract"
import { ClientError } from "./client-error"

type RawClient = HttpApiClient.ForApi<typeof ClientApi>

const mapClientError = <E>(error: E) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : error

const Endpoint0_0 = (raw: RawClient["server.health"]) => () =>
  raw["health.get"]({}).pipe(Effect.mapError(mapClientError))

const adaptGroup0 = (raw: RawClient["server.health"]) => ({ get: Endpoint0_0(raw) })

type Endpoint1_0Request = Parameters<RawClient["server.location"]["location.get"]>[0]
type Endpoint1_0Input = { readonly location?: Endpoint1_0Request["query"]["location"] }
const Endpoint1_0 = (raw: RawClient["server.location"]) => (input?: Endpoint1_0Input) =>
  raw["location.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup1 = (raw: RawClient["server.location"]) => ({ get: Endpoint1_0(raw) })

type Endpoint2_0Request = Parameters<RawClient["server.agent"]["agent.list"]>[0]
type Endpoint2_0Input = { readonly location?: Endpoint2_0Request["query"]["location"] }
const Endpoint2_0 = (raw: RawClient["server.agent"]) => (input?: Endpoint2_0Input) =>
  raw["agent.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup2 = (raw: RawClient["server.agent"]) => ({ list: Endpoint2_0(raw) })

type Endpoint3_0Request = Parameters<RawClient["server.session"]["session.list"]>[0]
type Endpoint3_0Input = {
  readonly workspace?: Endpoint3_0Request["query"]["workspace"]
  readonly limit?: Endpoint3_0Request["query"]["limit"]
  readonly order?: Endpoint3_0Request["query"]["order"]
  readonly search?: Endpoint3_0Request["query"]["search"]
  readonly directory?: Endpoint3_0Request["query"]["directory"]
  readonly project?: Endpoint3_0Request["query"]["project"]
  readonly subpath?: Endpoint3_0Request["query"]["subpath"]
  readonly cursor?: Endpoint3_0Request["query"]["cursor"]
}
const Endpoint3_0 = (raw: RawClient["server.session"]) => (input?: Endpoint3_0Input) =>
  raw["session.list"]({
    query: {
      workspace: input?.["workspace"],
      limit: input?.["limit"],
      order: input?.["order"],
      search: input?.["search"],
      directory: input?.["directory"],
      project: input?.["project"],
      subpath: input?.["subpath"],
      cursor: input?.["cursor"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_1Request = Parameters<RawClient["server.session"]["session.create"]>[0]
type Endpoint3_1Input = {
  readonly id?: Endpoint3_1Request["payload"]["id"]
  readonly agent?: Endpoint3_1Request["payload"]["agent"]
  readonly model?: Endpoint3_1Request["payload"]["model"]
  readonly location?: Endpoint3_1Request["payload"]["location"]
}
const Endpoint3_1 = (raw: RawClient["server.session"]) => (input?: Endpoint3_1Input) =>
  raw["session.create"]({
    payload: { id: input?.["id"], agent: input?.["agent"], model: input?.["model"], location: input?.["location"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const Endpoint3_2 = (raw: RawClient["server.session"]) => () =>
  raw["session.active"]({}).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_3Request = Parameters<RawClient["server.session"]["session.get"]>[0]
type Endpoint3_3Input = { readonly sessionID: Endpoint3_3Request["params"]["sessionID"] }
const Endpoint3_3 = (raw: RawClient["server.session"]) => (input: Endpoint3_3Input) =>
  raw["session.get"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_4Request = Parameters<RawClient["server.session"]["session.switchAgent"]>[0]
type Endpoint3_4Input = {
  readonly sessionID: Endpoint3_4Request["params"]["sessionID"]
  readonly agent: Endpoint3_4Request["payload"]["agent"]
}
const Endpoint3_4 = (raw: RawClient["server.session"]) => (input: Endpoint3_4Input) =>
  raw["session.switchAgent"]({ params: { sessionID: input["sessionID"] }, payload: { agent: input["agent"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint3_5Request = Parameters<RawClient["server.session"]["session.switchModel"]>[0]
type Endpoint3_5Input = {
  readonly sessionID: Endpoint3_5Request["params"]["sessionID"]
  readonly model: Endpoint3_5Request["payload"]["model"]
}
const Endpoint3_5 = (raw: RawClient["server.session"]) => (input: Endpoint3_5Input) =>
  raw["session.switchModel"]({ params: { sessionID: input["sessionID"] }, payload: { model: input["model"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint3_6Request = Parameters<RawClient["server.session"]["session.prompt"]>[0]
type Endpoint3_6Input = {
  readonly sessionID: Endpoint3_6Request["params"]["sessionID"]
  readonly id?: Endpoint3_6Request["payload"]["id"]
  readonly prompt: Endpoint3_6Request["payload"]["prompt"]
  readonly delivery?: Endpoint3_6Request["payload"]["delivery"]
  readonly resume?: Endpoint3_6Request["payload"]["resume"]
  readonly contextAttachments?: Endpoint3_6Request["payload"]["contextAttachments"]
}
const Endpoint3_6 = (raw: RawClient["server.session"]) => (input: Endpoint3_6Input) =>
  raw["session.prompt"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      prompt: input["prompt"],
      delivery: input["delivery"],
      resume: input["resume"],
      contextAttachments: input["contextAttachments"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_7Request = Parameters<RawClient["server.session"]["session.compact"]>[0]
type Endpoint3_7Input = { readonly sessionID: Endpoint3_7Request["params"]["sessionID"] }
const Endpoint3_7 = (raw: RawClient["server.session"]) => (input: Endpoint3_7Input) =>
  raw["session.compact"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_8Request = Parameters<RawClient["server.session"]["session.wait"]>[0]
type Endpoint3_8Input = { readonly sessionID: Endpoint3_8Request["params"]["sessionID"] }
const Endpoint3_8 = (raw: RawClient["server.session"]) => (input: Endpoint3_8Input) =>
  raw["session.wait"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_9Request = Parameters<RawClient["server.session"]["session.revert.stage"]>[0]
type Endpoint3_9Input = {
  readonly sessionID: Endpoint3_9Request["params"]["sessionID"]
  readonly messageID: Endpoint3_9Request["payload"]["messageID"]
  readonly files?: Endpoint3_9Request["payload"]["files"]
}
const Endpoint3_9 = (raw: RawClient["server.session"]) => (input: Endpoint3_9Input) =>
  raw["session.revert.stage"]({
    params: { sessionID: input["sessionID"] },
    payload: { messageID: input["messageID"], files: input["files"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_10Request = Parameters<RawClient["server.session"]["session.revert.clear"]>[0]
type Endpoint3_10Input = { readonly sessionID: Endpoint3_10Request["params"]["sessionID"] }
const Endpoint3_10 = (raw: RawClient["server.session"]) => (input: Endpoint3_10Input) =>
  raw["session.revert.clear"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_11Request = Parameters<RawClient["server.session"]["session.revert.commit"]>[0]
type Endpoint3_11Input = { readonly sessionID: Endpoint3_11Request["params"]["sessionID"] }
const Endpoint3_11 = (raw: RawClient["server.session"]) => (input: Endpoint3_11Input) =>
  raw["session.revert.commit"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_12Request = Parameters<RawClient["server.session"]["session.context"]>[0]
type Endpoint3_12Input = { readonly sessionID: Endpoint3_12Request["params"]["sessionID"] }
const Endpoint3_12 = (raw: RawClient["server.session"]) => (input: Endpoint3_12Input) =>
  raw["session.context"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_13Request = Parameters<RawClient["server.session"]["session.history"]>[0]
type Endpoint3_13Input = {
  readonly sessionID: Endpoint3_13Request["params"]["sessionID"]
  readonly limit?: Endpoint3_13Request["query"]["limit"]
  readonly after?: Endpoint3_13Request["query"]["after"]
}
const Endpoint3_13 = (raw: RawClient["server.session"]) => (input: Endpoint3_13Input) =>
  raw["session.history"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], after: input["after"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_14Request = Parameters<RawClient["server.session"]["session.events"]>[0]
type Endpoint3_14Input = {
  readonly sessionID: Endpoint3_14Request["params"]["sessionID"]
  readonly after?: Endpoint3_14Request["query"]["after"]
}
const Endpoint3_14 = (raw: RawClient["server.session"]) => (input: Endpoint3_14Input) =>
  Stream.unwrap(
    raw["session.events"]({ params: { sessionID: input["sessionID"] }, query: { after: input["after"] } }).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

type Endpoint3_15Request = Parameters<RawClient["server.session"]["session.interrupt"]>[0]
type Endpoint3_15Input = { readonly sessionID: Endpoint3_15Request["params"]["sessionID"] }
const Endpoint3_15 = (raw: RawClient["server.session"]) => (input: Endpoint3_15Input) =>
  raw["session.interrupt"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_16Request = Parameters<RawClient["server.session"]["session.message"]>[0]
type Endpoint3_16Input = {
  readonly sessionID: Endpoint3_16Request["params"]["sessionID"]
  readonly messageID: Endpoint3_16Request["params"]["messageID"]
}
const Endpoint3_16 = (raw: RawClient["server.session"]) => (input: Endpoint3_16Input) =>
  raw["session.message"]({ params: { sessionID: input["sessionID"], messageID: input["messageID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const adaptGroup3 = (raw: RawClient["server.session"]) => ({
  list: Endpoint3_0(raw),
  create: Endpoint3_1(raw),
  active: Endpoint3_2(raw),
  get: Endpoint3_3(raw),
  switchAgent: Endpoint3_4(raw),
  switchModel: Endpoint3_5(raw),
  prompt: Endpoint3_6(raw),
  compact: Endpoint3_7(raw),
  wait: Endpoint3_8(raw),
  stage: Endpoint3_9(raw),
  clear: Endpoint3_10(raw),
  commit: Endpoint3_11(raw),
  context: Endpoint3_12(raw),
  history: Endpoint3_13(raw),
  events: Endpoint3_14(raw),
  interrupt: Endpoint3_15(raw),
  message: Endpoint3_16(raw),
})

type Endpoint4_0Request = Parameters<RawClient["server.message"]["session.messages"]>[0]
type Endpoint4_0Input = {
  readonly sessionID: Endpoint4_0Request["params"]["sessionID"]
  readonly limit?: Endpoint4_0Request["query"]["limit"]
  readonly order?: Endpoint4_0Request["query"]["order"]
  readonly cursor?: Endpoint4_0Request["query"]["cursor"]
}
const Endpoint4_0 = (raw: RawClient["server.message"]) => (input: Endpoint4_0Input) =>
  raw["session.messages"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], order: input["order"], cursor: input["cursor"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup4 = (raw: RawClient["server.message"]) => ({ list: Endpoint4_0(raw) })

type Endpoint5_0Request = Parameters<RawClient["server.model"]["model.list"]>[0]
type Endpoint5_0Input = { readonly location?: Endpoint5_0Request["query"]["location"] }
const Endpoint5_0 = (raw: RawClient["server.model"]) => (input?: Endpoint5_0Input) =>
  raw["model.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup5 = (raw: RawClient["server.model"]) => ({ list: Endpoint5_0(raw) })

type Endpoint6_0Request = Parameters<RawClient["server.provider"]["provider.list"]>[0]
type Endpoint6_0Input = { readonly location?: Endpoint6_0Request["query"]["location"] }
const Endpoint6_0 = (raw: RawClient["server.provider"]) => (input?: Endpoint6_0Input) =>
  raw["provider.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint6_1Request = Parameters<RawClient["server.provider"]["provider.get"]>[0]
type Endpoint6_1Input = {
  readonly providerID: Endpoint6_1Request["params"]["providerID"]
  readonly location?: Endpoint6_1Request["query"]["location"]
}
const Endpoint6_1 = (raw: RawClient["server.provider"]) => (input: Endpoint6_1Input) =>
  raw["provider.get"]({ params: { providerID: input["providerID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup6 = (raw: RawClient["server.provider"]) => ({ list: Endpoint6_0(raw), get: Endpoint6_1(raw) })

type Endpoint7_0Request = Parameters<RawClient["server.integration"]["integration.list"]>[0]
type Endpoint7_0Input = { readonly location?: Endpoint7_0Request["query"]["location"] }
const Endpoint7_0 = (raw: RawClient["server.integration"]) => (input?: Endpoint7_0Input) =>
  raw["integration.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint7_1Request = Parameters<RawClient["server.integration"]["integration.get"]>[0]
type Endpoint7_1Input = {
  readonly integrationID: Endpoint7_1Request["params"]["integrationID"]
  readonly location?: Endpoint7_1Request["query"]["location"]
}
const Endpoint7_1 = (raw: RawClient["server.integration"]) => (input: Endpoint7_1Input) =>
  raw["integration.get"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint7_2Request = Parameters<RawClient["server.integration"]["integration.connect.key"]>[0]
type Endpoint7_2Input = {
  readonly integrationID: Endpoint7_2Request["params"]["integrationID"]
  readonly location?: Endpoint7_2Request["query"]["location"]
  readonly key: Endpoint7_2Request["payload"]["key"]
  readonly label?: Endpoint7_2Request["payload"]["label"]
}
const Endpoint7_2 = (raw: RawClient["server.integration"]) => (input: Endpoint7_2Input) =>
  raw["integration.connect.key"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { key: input["key"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint7_3Request = Parameters<RawClient["server.integration"]["integration.connect.oauth"]>[0]
type Endpoint7_3Input = {
  readonly integrationID: Endpoint7_3Request["params"]["integrationID"]
  readonly location?: Endpoint7_3Request["query"]["location"]
  readonly methodID: Endpoint7_3Request["payload"]["methodID"]
  readonly inputs: Endpoint7_3Request["payload"]["inputs"]
  readonly label?: Endpoint7_3Request["payload"]["label"]
}
const Endpoint7_3 = (raw: RawClient["server.integration"]) => (input: Endpoint7_3Input) =>
  raw["integration.connect.oauth"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { methodID: input["methodID"], inputs: input["inputs"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint7_4Request = Parameters<RawClient["server.integration"]["integration.attempt.status"]>[0]
type Endpoint7_4Input = {
  readonly attemptID: Endpoint7_4Request["params"]["attemptID"]
  readonly location?: Endpoint7_4Request["query"]["location"]
}
const Endpoint7_4 = (raw: RawClient["server.integration"]) => (input: Endpoint7_4Input) =>
  raw["integration.attempt.status"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint7_5Request = Parameters<RawClient["server.integration"]["integration.attempt.complete"]>[0]
type Endpoint7_5Input = {
  readonly attemptID: Endpoint7_5Request["params"]["attemptID"]
  readonly location?: Endpoint7_5Request["query"]["location"]
  readonly code?: Endpoint7_5Request["payload"]["code"]
}
const Endpoint7_5 = (raw: RawClient["server.integration"]) => (input: Endpoint7_5Input) =>
  raw["integration.attempt.complete"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
    payload: { code: input["code"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint7_6Request = Parameters<RawClient["server.integration"]["integration.attempt.cancel"]>[0]
type Endpoint7_6Input = {
  readonly attemptID: Endpoint7_6Request["params"]["attemptID"]
  readonly location?: Endpoint7_6Request["query"]["location"]
}
const Endpoint7_6 = (raw: RawClient["server.integration"]) => (input: Endpoint7_6Input) =>
  raw["integration.attempt.cancel"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup7 = (raw: RawClient["server.integration"]) => ({
  list: Endpoint7_0(raw),
  get: Endpoint7_1(raw),
  connectKey: Endpoint7_2(raw),
  connectOauth: Endpoint7_3(raw),
  attemptStatus: Endpoint7_4(raw),
  attemptComplete: Endpoint7_5(raw),
  attemptCancel: Endpoint7_6(raw),
})

type Endpoint8_0Request = Parameters<RawClient["server.credential"]["credential.update"]>[0]
type Endpoint8_0Input = {
  readonly credentialID: Endpoint8_0Request["params"]["credentialID"]
  readonly location?: Endpoint8_0Request["query"]["location"]
  readonly label: Endpoint8_0Request["payload"]["label"]
}
const Endpoint8_0 = (raw: RawClient["server.credential"]) => (input: Endpoint8_0Input) =>
  raw["credential.update"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
    payload: { label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_1Request = Parameters<RawClient["server.credential"]["credential.remove"]>[0]
type Endpoint8_1Input = {
  readonly credentialID: Endpoint8_1Request["params"]["credentialID"]
  readonly location?: Endpoint8_1Request["query"]["location"]
}
const Endpoint8_1 = (raw: RawClient["server.credential"]) => (input: Endpoint8_1Input) =>
  raw["credential.remove"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup8 = (raw: RawClient["server.credential"]) => ({ update: Endpoint8_0(raw), remove: Endpoint8_1(raw) })

type Endpoint9_0Request = Parameters<RawClient["server.permission"]["permission.request.list"]>[0]
type Endpoint9_0Input = { readonly location?: Endpoint9_0Request["query"]["location"] }
const Endpoint9_0 = (raw: RawClient["server.permission"]) => (input?: Endpoint9_0Input) =>
  raw["permission.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint9_1Request = Parameters<RawClient["server.permission"]["permission.saved.list"]>[0]
type Endpoint9_1Input = { readonly projectID?: Endpoint9_1Request["query"]["projectID"] }
const Endpoint9_1 = (raw: RawClient["server.permission"]) => (input?: Endpoint9_1Input) =>
  raw["permission.saved.list"]({ query: { projectID: input?.["projectID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint9_2Request = Parameters<RawClient["server.permission"]["permission.saved.remove"]>[0]
type Endpoint9_2Input = { readonly id: Endpoint9_2Request["params"]["id"] }
const Endpoint9_2 = (raw: RawClient["server.permission"]) => (input: Endpoint9_2Input) =>
  raw["permission.saved.remove"]({ params: { id: input["id"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint9_3Request = Parameters<RawClient["server.permission"]["session.permission.create"]>[0]
type Endpoint9_3Input = {
  readonly sessionID: Endpoint9_3Request["params"]["sessionID"]
  readonly id?: Endpoint9_3Request["payload"]["id"]
  readonly action: Endpoint9_3Request["payload"]["action"]
  readonly resources: Endpoint9_3Request["payload"]["resources"]
  readonly save?: Endpoint9_3Request["payload"]["save"]
  readonly metadata?: Endpoint9_3Request["payload"]["metadata"]
  readonly source?: Endpoint9_3Request["payload"]["source"]
  readonly agent?: Endpoint9_3Request["payload"]["agent"]
}
const Endpoint9_3 = (raw: RawClient["server.permission"]) => (input: Endpoint9_3Input) =>
  raw["session.permission.create"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      action: input["action"],
      resources: input["resources"],
      save: input["save"],
      metadata: input["metadata"],
      source: input["source"],
      agent: input["agent"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint9_4Request = Parameters<RawClient["server.permission"]["session.permission.list"]>[0]
type Endpoint9_4Input = { readonly sessionID: Endpoint9_4Request["params"]["sessionID"] }
const Endpoint9_4 = (raw: RawClient["server.permission"]) => (input: Endpoint9_4Input) =>
  raw["session.permission.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint9_5Request = Parameters<RawClient["server.permission"]["session.permission.get"]>[0]
type Endpoint9_5Input = {
  readonly sessionID: Endpoint9_5Request["params"]["sessionID"]
  readonly requestID: Endpoint9_5Request["params"]["requestID"]
}
const Endpoint9_5 = (raw: RawClient["server.permission"]) => (input: Endpoint9_5Input) =>
  raw["session.permission.get"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint9_6Request = Parameters<RawClient["server.permission"]["session.permission.reply"]>[0]
type Endpoint9_6Input = {
  readonly sessionID: Endpoint9_6Request["params"]["sessionID"]
  readonly requestID: Endpoint9_6Request["params"]["requestID"]
  readonly reply: Endpoint9_6Request["payload"]["reply"]
  readonly message?: Endpoint9_6Request["payload"]["message"]
}
const Endpoint9_6 = (raw: RawClient["server.permission"]) => (input: Endpoint9_6Input) =>
  raw["session.permission.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { reply: input["reply"], message: input["message"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup9 = (raw: RawClient["server.permission"]) => ({
  listRequests: Endpoint9_0(raw),
  listSaved: Endpoint9_1(raw),
  removeSaved: Endpoint9_2(raw),
  create: Endpoint9_3(raw),
  list: Endpoint9_4(raw),
  get: Endpoint9_5(raw),
  reply: Endpoint9_6(raw),
})

type Endpoint10_0Request = Parameters<RawClient["server.fs"]["fs.list"]>[0]
type Endpoint10_0Input = {
  readonly location?: Endpoint10_0Request["query"]["location"]
  readonly path?: Endpoint10_0Request["query"]["path"]
}
const Endpoint10_0 = (raw: RawClient["server.fs"]) => (input?: Endpoint10_0Input) =>
  raw["fs.list"]({ query: { location: input?.["location"], path: input?.["path"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint10_1Request = Parameters<RawClient["server.fs"]["fs.find"]>[0]
type Endpoint10_1Input = {
  readonly location?: Endpoint10_1Request["query"]["location"]
  readonly query: Endpoint10_1Request["query"]["query"]
  readonly type?: Endpoint10_1Request["query"]["type"]
  readonly limit?: Endpoint10_1Request["query"]["limit"]
}
const Endpoint10_1 = (raw: RawClient["server.fs"]) => (input: Endpoint10_1Input) =>
  raw["fs.find"]({
    query: { location: input["location"], query: input["query"], type: input["type"], limit: input["limit"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup10 = (raw: RawClient["server.fs"]) => ({ list: Endpoint10_0(raw), find: Endpoint10_1(raw) })

type Endpoint11_0Request = Parameters<RawClient["server.command"]["command.list"]>[0]
type Endpoint11_0Input = { readonly location?: Endpoint11_0Request["query"]["location"] }
const Endpoint11_0 = (raw: RawClient["server.command"]) => (input?: Endpoint11_0Input) =>
  raw["command.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup11 = (raw: RawClient["server.command"]) => ({ list: Endpoint11_0(raw) })

type Endpoint12_0Request = Parameters<RawClient["server.skill"]["skill.candidates"]>[0]
type Endpoint12_0Input = {
  readonly location?: Endpoint12_0Request["query"]["location"]
  readonly agent?: Endpoint12_0Request["query"]["agent"]
}
const Endpoint12_0 = (raw: RawClient["server.skill"]) => (input?: Endpoint12_0Input) =>
  raw["skill.candidates"]({ query: { location: input?.["location"], agent: input?.["agent"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint12_1Request = Parameters<RawClient["server.skill"]["skill.list"]>[0]
type Endpoint12_1Input = { readonly location?: Endpoint12_1Request["query"]["location"] }
const Endpoint12_1 = (raw: RawClient["server.skill"]) => (input?: Endpoint12_1Input) =>
  raw["skill.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup12 = (raw: RawClient["server.skill"]) => ({ candidates: Endpoint12_0(raw), list: Endpoint12_1(raw) })

const Endpoint13_0 = (raw: RawClient["server.event"]) => () =>
  Stream.unwrap(
    raw["event.subscribe"]({}).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

const adaptGroup13 = (raw: RawClient["server.event"]) => ({ subscribe: Endpoint13_0(raw) })

type Endpoint14_0Request = Parameters<RawClient["server.pty"]["pty.list"]>[0]
type Endpoint14_0Input = { readonly location?: Endpoint14_0Request["query"]["location"] }
const Endpoint14_0 = (raw: RawClient["server.pty"]) => (input?: Endpoint14_0Input) =>
  raw["pty.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint14_1Request = Parameters<RawClient["server.pty"]["pty.create"]>[0]
type Endpoint14_1Input = {
  readonly location?: Endpoint14_1Request["query"]["location"]
  readonly command?: Endpoint14_1Request["payload"]["command"]
  readonly args?: Endpoint14_1Request["payload"]["args"]
  readonly cwd?: Endpoint14_1Request["payload"]["cwd"]
  readonly title?: Endpoint14_1Request["payload"]["title"]
  readonly env?: Endpoint14_1Request["payload"]["env"]
}
const Endpoint14_1 = (raw: RawClient["server.pty"]) => (input?: Endpoint14_1Input) =>
  raw["pty.create"]({
    query: { location: input?.["location"] },
    payload: {
      command: input?.["command"],
      args: input?.["args"],
      cwd: input?.["cwd"],
      title: input?.["title"],
      env: input?.["env"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint14_2Request = Parameters<RawClient["server.pty"]["pty.get"]>[0]
type Endpoint14_2Input = {
  readonly ptyID: Endpoint14_2Request["params"]["ptyID"]
  readonly location?: Endpoint14_2Request["query"]["location"]
}
const Endpoint14_2 = (raw: RawClient["server.pty"]) => (input: Endpoint14_2Input) =>
  raw["pty.get"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint14_3Request = Parameters<RawClient["server.pty"]["pty.update"]>[0]
type Endpoint14_3Input = {
  readonly ptyID: Endpoint14_3Request["params"]["ptyID"]
  readonly location?: Endpoint14_3Request["query"]["location"]
  readonly title?: Endpoint14_3Request["payload"]["title"]
  readonly size?: Endpoint14_3Request["payload"]["size"]
}
const Endpoint14_3 = (raw: RawClient["server.pty"]) => (input: Endpoint14_3Input) =>
  raw["pty.update"]({
    params: { ptyID: input["ptyID"] },
    query: { location: input["location"] },
    payload: { title: input["title"], size: input["size"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint14_4Request = Parameters<RawClient["server.pty"]["pty.remove"]>[0]
type Endpoint14_4Input = {
  readonly ptyID: Endpoint14_4Request["params"]["ptyID"]
  readonly location?: Endpoint14_4Request["query"]["location"]
}
const Endpoint14_4 = (raw: RawClient["server.pty"]) => (input: Endpoint14_4Input) =>
  raw["pty.remove"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup14 = (raw: RawClient["server.pty"]) => ({
  list: Endpoint14_0(raw),
  create: Endpoint14_1(raw),
  get: Endpoint14_2(raw),
  update: Endpoint14_3(raw),
  remove: Endpoint14_4(raw),
})

type Endpoint15_0Request = Parameters<RawClient["server.question"]["question.request.list"]>[0]
type Endpoint15_0Input = { readonly location?: Endpoint15_0Request["query"]["location"] }
const Endpoint15_0 = (raw: RawClient["server.question"]) => (input?: Endpoint15_0Input) =>
  raw["question.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint15_1Request = Parameters<RawClient["server.question"]["session.question.list"]>[0]
type Endpoint15_1Input = { readonly sessionID: Endpoint15_1Request["params"]["sessionID"] }
const Endpoint15_1 = (raw: RawClient["server.question"]) => (input: Endpoint15_1Input) =>
  raw["session.question.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint15_2Request = Parameters<RawClient["server.question"]["session.question.reply"]>[0]
type Endpoint15_2Input = {
  readonly sessionID: Endpoint15_2Request["params"]["sessionID"]
  readonly requestID: Endpoint15_2Request["params"]["requestID"]
  readonly answers: Endpoint15_2Request["payload"]["answers"]
}
const Endpoint15_2 = (raw: RawClient["server.question"]) => (input: Endpoint15_2Input) =>
  raw["session.question.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { answers: input["answers"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint15_3Request = Parameters<RawClient["server.question"]["session.question.reject"]>[0]
type Endpoint15_3Input = {
  readonly sessionID: Endpoint15_3Request["params"]["sessionID"]
  readonly requestID: Endpoint15_3Request["params"]["requestID"]
}
const Endpoint15_3 = (raw: RawClient["server.question"]) => (input: Endpoint15_3Input) =>
  raw["session.question.reject"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup15 = (raw: RawClient["server.question"]) => ({
  listRequests: Endpoint15_0(raw),
  list: Endpoint15_1(raw),
  reply: Endpoint15_2(raw),
  reject: Endpoint15_3(raw),
})

type Endpoint16_0Request = Parameters<RawClient["server.reference"]["reference.list"]>[0]
type Endpoint16_0Input = { readonly location?: Endpoint16_0Request["query"]["location"] }
const Endpoint16_0 = (raw: RawClient["server.reference"]) => (input?: Endpoint16_0Input) =>
  raw["reference.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup16 = (raw: RawClient["server.reference"]) => ({ list: Endpoint16_0(raw) })

type Endpoint17_0Request = Parameters<RawClient["server.projectCopy"]["projectCopy.create"]>[0]
type Endpoint17_0Input = {
  readonly projectID: Endpoint17_0Request["params"]["projectID"]
  readonly location?: Endpoint17_0Request["query"]["location"]
  readonly strategy: Endpoint17_0Request["payload"]["strategy"]
  readonly directory: Endpoint17_0Request["payload"]["directory"]
  readonly name?: Endpoint17_0Request["payload"]["name"]
}
const Endpoint17_0 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint17_0Input) =>
  raw["projectCopy.create"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { strategy: input["strategy"], directory: input["directory"], name: input["name"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint17_1Request = Parameters<RawClient["server.projectCopy"]["projectCopy.remove"]>[0]
type Endpoint17_1Input = {
  readonly projectID: Endpoint17_1Request["params"]["projectID"]
  readonly location?: Endpoint17_1Request["query"]["location"]
  readonly directory: Endpoint17_1Request["payload"]["directory"]
  readonly force: Endpoint17_1Request["payload"]["force"]
}
const Endpoint17_1 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint17_1Input) =>
  raw["projectCopy.remove"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { directory: input["directory"], force: input["force"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint17_2Request = Parameters<RawClient["server.projectCopy"]["projectCopy.refresh"]>[0]
type Endpoint17_2Input = {
  readonly projectID: Endpoint17_2Request["params"]["projectID"]
  readonly location?: Endpoint17_2Request["query"]["location"]
}
const Endpoint17_2 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint17_2Input) =>
  raw["projectCopy.refresh"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup17 = (raw: RawClient["server.projectCopy"]) => ({
  create: Endpoint17_0(raw),
  remove: Endpoint17_1(raw),
  refresh: Endpoint17_2(raw),
})

const Endpoint18_0 = (raw: RawClient["server.workspace"]) => () =>
  raw["workspace.list"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint18_1Request = Parameters<RawClient["server.workspace"]["workspace.create"]>[0]
type Endpoint18_1Input = { readonly name: Endpoint18_1Request["payload"]["name"] }
const Endpoint18_1 = (raw: RawClient["server.workspace"]) => (input: Endpoint18_1Input) =>
  raw["workspace.create"]({ payload: { name: input["name"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint18_2Request = Parameters<RawClient["server.workspace"]["workspace.get"]>[0]
type Endpoint18_2Input = { readonly id: Endpoint18_2Request["params"]["id"] }
const Endpoint18_2 = (raw: RawClient["server.workspace"]) => (input: Endpoint18_2Input) =>
  raw["workspace.get"]({ params: { id: input["id"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint18_3Request = Parameters<RawClient["server.workspace"]["workspace.update"]>[0]
type Endpoint18_3Input = {
  readonly id: Endpoint18_3Request["payload"]["id"]
  readonly patch: Endpoint18_3Request["payload"]["patch"]
}
const Endpoint18_3 = (raw: RawClient["server.workspace"]) => (input: Endpoint18_3Input) =>
  raw["workspace.update"]({ payload: { id: input["id"], patch: input["patch"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint18_4Request = Parameters<RawClient["server.workspace"]["workspace.remove"]>[0]
type Endpoint18_4Input = { readonly id: Endpoint18_4Request["params"]["id"] }
const Endpoint18_4 = (raw: RawClient["server.workspace"]) => (input: Endpoint18_4Input) =>
  raw["workspace.remove"]({ params: { id: input["id"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint18_5Request = Parameters<RawClient["server.workspace"]["workspace.duplicate"]>[0]
type Endpoint18_5Input = { readonly id: Endpoint18_5Request["params"]["id"] }
const Endpoint18_5 = (raw: RawClient["server.workspace"]) => (input: Endpoint18_5Input) =>
  raw["workspace.duplicate"]({ params: { id: input["id"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint18_6Request = Parameters<RawClient["server.workspace"]["workspace.layout.get"]>[0]
type Endpoint18_6Input = {
  readonly workspaceID: Endpoint18_6Request["payload"]["workspaceID"]
  readonly tuple: Endpoint18_6Request["payload"]["tuple"]
  readonly clientID: Endpoint18_6Request["payload"]["clientID"]
}
const Endpoint18_6 = (raw: RawClient["server.workspace"]) => (input: Endpoint18_6Input) =>
  raw["workspace.layout.get"]({
    payload: { workspaceID: input["workspaceID"], tuple: input["tuple"], clientID: input["clientID"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint18_7Request = Parameters<RawClient["server.workspace"]["workspace.layout.save"]>[0]
type Endpoint18_7Input = {
  readonly workspaceID: Endpoint18_7Request["payload"]["workspaceID"]
  readonly tuple: Endpoint18_7Request["payload"]["tuple"]
  readonly blocks: Endpoint18_7Request["payload"]["blocks"]
  readonly expectedRevision: Endpoint18_7Request["payload"]["expectedRevision"]
  readonly clientID: Endpoint18_7Request["payload"]["clientID"]
}
const Endpoint18_7 = (raw: RawClient["server.workspace"]) => (input: Endpoint18_7Input) =>
  raw["workspace.layout.save"]({
    payload: {
      workspaceID: input["workspaceID"],
      tuple: input["tuple"],
      blocks: input["blocks"],
      expectedRevision: input["expectedRevision"],
      clientID: input["clientID"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint18_8Request = Parameters<RawClient["server.workspace"]["workspace.functionality.list"]>[0]
type Endpoint18_8Input = { readonly workspaceID: Endpoint18_8Request["params"]["workspaceID"] }
const Endpoint18_8 = (raw: RawClient["server.workspace"]) => (input: Endpoint18_8Input) =>
  raw["workspace.functionality.list"]({ params: { workspaceID: input["workspaceID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup18 = (raw: RawClient["server.workspace"]) => ({
  list: Endpoint18_0(raw),
  create: Endpoint18_1(raw),
  get: Endpoint18_2(raw),
  update: Endpoint18_3(raw),
  remove: Endpoint18_4(raw),
  duplicate: Endpoint18_5(raw),
  layoutGet: Endpoint18_6(raw),
  layoutSave: Endpoint18_7(raw),
  functionalityList: Endpoint18_8(raw),
})

type Endpoint19_0Request = Parameters<RawClient["server.workspace.masterAgent"]["workspace.masterAgent.get"]>[0]
type Endpoint19_0Input = {
  readonly workspaceID: Endpoint19_0Request["params"]["workspaceID"]
  readonly blockID: Endpoint19_0Request["params"]["blockID"]
}
const Endpoint19_0 = (raw: RawClient["server.workspace.masterAgent"]) => (input: Endpoint19_0Input) =>
  raw["workspace.masterAgent.get"]({ params: { workspaceID: input["workspaceID"], blockID: input["blockID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint19_1Request = Parameters<RawClient["server.workspace.masterAgent"]["workspace.masterAgent.ensure"]>[0]
type Endpoint19_1Input = {
  readonly workspaceID: Endpoint19_1Request["params"]["workspaceID"]
  readonly blockID: Endpoint19_1Request["params"]["blockID"]
}
const Endpoint19_1 = (raw: RawClient["server.workspace.masterAgent"]) => (input: Endpoint19_1Input) =>
  raw["workspace.masterAgent.ensure"]({
    params: { workspaceID: input["workspaceID"], blockID: input["blockID"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_2Request = Parameters<RawClient["server.workspace.masterAgent"]["workspace.masterAgent.reset"]>[0]
type Endpoint19_2Input = {
  readonly workspaceID: Endpoint19_2Request["params"]["workspaceID"]
  readonly blockID: Endpoint19_2Request["params"]["blockID"]
  readonly expectedSessionID: Endpoint19_2Request["payload"]["expectedSessionID"]
  readonly expectedRevision: Endpoint19_2Request["payload"]["expectedRevision"]
}
const Endpoint19_2 = (raw: RawClient["server.workspace.masterAgent"]) => (input: Endpoint19_2Input) =>
  raw["workspace.masterAgent.reset"]({
    params: { workspaceID: input["workspaceID"], blockID: input["blockID"] },
    payload: { expectedSessionID: input["expectedSessionID"], expectedRevision: input["expectedRevision"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup19 = (raw: RawClient["server.workspace.masterAgent"]) => ({
  get: Endpoint19_0(raw),
  ensure: Endpoint19_1(raw),
  reset: Endpoint19_2(raw),
})

type Endpoint20_0Request = Parameters<RawClient["server.workspace.chatRelay"]["workspace.chatRelay.get"]>[0]
type Endpoint20_0Input = {
  readonly workspaceID: Endpoint20_0Request["params"]["workspaceID"]
  readonly blockID: Endpoint20_0Request["params"]["blockID"]
}
const Endpoint20_0 = (raw: RawClient["server.workspace.chatRelay"]) => (input: Endpoint20_0Input) =>
  raw["workspace.chatRelay.get"]({ params: { workspaceID: input["workspaceID"], blockID: input["blockID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint20_1Request = Parameters<RawClient["server.workspace.chatRelay"]["workspace.chatRelay.ensure"]>[0]
type Endpoint20_1Input = {
  readonly workspaceID: Endpoint20_1Request["params"]["workspaceID"]
  readonly blockID: Endpoint20_1Request["params"]["blockID"]
}
const Endpoint20_1 = (raw: RawClient["server.workspace.chatRelay"]) => (input: Endpoint20_1Input) =>
  raw["workspace.chatRelay.ensure"]({ params: { workspaceID: input["workspaceID"], blockID: input["blockID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint20_2Request = Parameters<RawClient["server.workspace.chatRelay"]["workspace.chatRelay.reset"]>[0]
type Endpoint20_2Input = {
  readonly workspaceID: Endpoint20_2Request["params"]["workspaceID"]
  readonly blockID: Endpoint20_2Request["params"]["blockID"]
  readonly expectedSessionID: Endpoint20_2Request["payload"]["expectedSessionID"]
  readonly expectedRevision: Endpoint20_2Request["payload"]["expectedRevision"]
}
const Endpoint20_2 = (raw: RawClient["server.workspace.chatRelay"]) => (input: Endpoint20_2Input) =>
  raw["workspace.chatRelay.reset"]({
    params: { workspaceID: input["workspaceID"], blockID: input["blockID"] },
    payload: { expectedSessionID: input["expectedSessionID"], expectedRevision: input["expectedRevision"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup20 = (raw: RawClient["server.workspace.chatRelay"]) => ({
  get: Endpoint20_0(raw),
  ensure: Endpoint20_1(raw),
  reset: Endpoint20_2(raw),
})

type Endpoint21_0Request = Parameters<RawClient["server.chatProxy"]["chatProxy.skills"]>[0]
type Endpoint21_0Input = {
  readonly workspaceID: Endpoint21_0Request["params"]["workspaceID"]
  readonly blockID: Endpoint21_0Request["params"]["blockID"]
}
const Endpoint21_0 = (raw: RawClient["server.chatProxy"]) => (input: Endpoint21_0Input) =>
  raw["chatProxy.skills"]({ params: { workspaceID: input["workspaceID"], blockID: input["blockID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint21_1Request = Parameters<RawClient["server.chatProxy"]["chatProxy.skillPreview"]>[0]
type Endpoint21_1Input = {
  readonly workspaceID: Endpoint21_1Request["params"]["workspaceID"]
  readonly blockID: Endpoint21_1Request["params"]["blockID"]
  readonly name: Endpoint21_1Request["query"]["name"]
  readonly contentHash: Endpoint21_1Request["query"]["contentHash"]
}
const Endpoint21_1 = (raw: RawClient["server.chatProxy"]) => (input: Endpoint21_1Input) =>
  raw["chatProxy.skillPreview"]({
    params: { workspaceID: input["workspaceID"], blockID: input["blockID"] },
    query: { name: input["name"], contentHash: input["contentHash"] },
  }).pipe(Effect.mapError(mapClientError))

const Endpoint21_2 = (raw: RawClient["server.chatProxy"]) => () =>
  raw["chatProxy.status"]({}).pipe(Effect.mapError(mapClientError))

const Endpoint21_3 = (raw: RawClient["server.chatProxy"]) => () =>
  raw["chatProxy.connect"]({}).pipe(Effect.mapError(mapClientError))

const Endpoint21_4 = (raw: RawClient["server.chatProxy"]) => () =>
  raw["chatProxy.open"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint21_5Request = Parameters<RawClient["server.chatProxy"]["chatProxy.relay"]>[0]
type Endpoint21_5Input = {
  readonly workspaceID: Endpoint21_5Request["params"]["workspaceID"]
  readonly blockID: Endpoint21_5Request["params"]["blockID"]
}
const Endpoint21_5 = (raw: RawClient["server.chatProxy"]) => (input: Endpoint21_5Input) =>
  raw["chatProxy.relay"]({ params: { workspaceID: input["workspaceID"], blockID: input["blockID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint21_6Request = Parameters<RawClient["server.chatProxy"]["chatProxy.ensure"]>[0]
type Endpoint21_6Input = {
  readonly workspaceID: Endpoint21_6Request["params"]["workspaceID"]
  readonly blockID: Endpoint21_6Request["params"]["blockID"]
}
const Endpoint21_6 = (raw: RawClient["server.chatProxy"]) => (input: Endpoint21_6Input) =>
  raw["chatProxy.ensure"]({ params: { workspaceID: input["workspaceID"], blockID: input["blockID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint21_7Request = Parameters<RawClient["server.chatProxy"]["chatProxy.reset"]>[0]
type Endpoint21_7Input = {
  readonly workspaceID: Endpoint21_7Request["params"]["workspaceID"]
  readonly blockID: Endpoint21_7Request["params"]["blockID"]
  readonly tabID?: Endpoint21_7Request["payload"]["tabID"]
}
const Endpoint21_7 = (raw: RawClient["server.chatProxy"]) => (input: Endpoint21_7Input) =>
  raw["chatProxy.reset"]({
    params: { workspaceID: input["workspaceID"], blockID: input["blockID"] },
    payload: { tabID: input["tabID"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint21_8Request = Parameters<RawClient["server.chatProxy"]["chatProxy.prompt"]>[0]
type Endpoint21_8Input = {
  readonly workspaceID: Endpoint21_8Request["params"]["workspaceID"]
  readonly blockID: Endpoint21_8Request["params"]["blockID"]
  readonly tabID: Endpoint21_8Request["payload"]["tabID"]
  readonly messageID: Endpoint21_8Request["payload"]["messageID"]
  readonly text: Endpoint21_8Request["payload"]["text"]
  readonly files?: Endpoint21_8Request["payload"]["files"]
  readonly contextAttachments?: Endpoint21_8Request["payload"]["contextAttachments"]
  readonly skills?: Endpoint21_8Request["payload"]["skills"]
}
const Endpoint21_8 = (raw: RawClient["server.chatProxy"]) => (input: Endpoint21_8Input) =>
  raw["chatProxy.prompt"]({
    params: { workspaceID: input["workspaceID"], blockID: input["blockID"] },
    payload: {
      tabID: input["tabID"],
      messageID: input["messageID"],
      text: input["text"],
      files: input["files"],
      contextAttachments: input["contextAttachments"],
      skills: input["skills"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint21_9Request = Parameters<RawClient["server.chatProxy"]["chatProxy.openRelay"]>[0]
type Endpoint21_9Input = {
  readonly workspaceID: Endpoint21_9Request["params"]["workspaceID"]
  readonly blockID: Endpoint21_9Request["params"]["blockID"]
  readonly tabID: Endpoint21_9Request["payload"]["tabID"]
}
const Endpoint21_9 = (raw: RawClient["server.chatProxy"]) => (input: Endpoint21_9Input) =>
  raw["chatProxy.openRelay"]({
    params: { workspaceID: input["workspaceID"], blockID: input["blockID"] },
    payload: { tabID: input["tabID"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint21_10Request = Parameters<RawClient["server.chatProxy"]["chatProxy.options"]>[0]
type Endpoint21_10Input = {
  readonly workspaceID: Endpoint21_10Request["params"]["workspaceID"]
  readonly blockID: Endpoint21_10Request["params"]["blockID"]
  readonly tabID: Endpoint21_10Request["payload"]["tabID"]
}
const Endpoint21_10 = (raw: RawClient["server.chatProxy"]) => (input: Endpoint21_10Input) =>
  raw["chatProxy.options"]({
    params: { workspaceID: input["workspaceID"], blockID: input["blockID"] },
    payload: { tabID: input["tabID"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint21_11Request = Parameters<RawClient["server.chatProxy"]["chatProxy.configure"]>[0]
type Endpoint21_11Input = {
  readonly workspaceID: Endpoint21_11Request["params"]["workspaceID"]
  readonly blockID: Endpoint21_11Request["params"]["blockID"]
  readonly tabID: Endpoint21_11Request["payload"]["tabID"]
  readonly model?: Endpoint21_11Request["payload"]["model"]
  readonly effort?: Endpoint21_11Request["payload"]["effort"]
}
const Endpoint21_11 = (raw: RawClient["server.chatProxy"]) => (input: Endpoint21_11Input) =>
  raw["chatProxy.configure"]({
    params: { workspaceID: input["workspaceID"], blockID: input["blockID"] },
    payload: { tabID: input["tabID"], model: input["model"], effort: input["effort"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup21 = (raw: RawClient["server.chatProxy"]) => ({
  skills: Endpoint21_0(raw),
  skillPreview: Endpoint21_1(raw),
  status: Endpoint21_2(raw),
  connect: Endpoint21_3(raw),
  open: Endpoint21_4(raw),
  relay: Endpoint21_5(raw),
  ensure: Endpoint21_6(raw),
  reset: Endpoint21_7(raw),
  prompt: Endpoint21_8(raw),
  openRelay: Endpoint21_9(raw),
  options: Endpoint21_10(raw),
  configure: Endpoint21_11(raw),
})

type Endpoint22_0Request = Parameters<RawClient["server.workspace.operatingChat"]["workspace.operatingChat.get"]>[0]
type Endpoint22_0Input = {
  readonly workspaceID: Endpoint22_0Request["params"]["workspaceID"]
  readonly blockID: Endpoint22_0Request["params"]["blockID"]
}
const Endpoint22_0 = (raw: RawClient["server.workspace.operatingChat"]) => (input: Endpoint22_0Input) =>
  raw["workspace.operatingChat.get"]({ params: { workspaceID: input["workspaceID"], blockID: input["blockID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint22_1Request = Parameters<RawClient["server.workspace.operatingChat"]["workspace.operatingChat.ensure"]>[0]
type Endpoint22_1Input = {
  readonly workspaceID: Endpoint22_1Request["params"]["workspaceID"]
  readonly blockID: Endpoint22_1Request["params"]["blockID"]
}
const Endpoint22_1 = (raw: RawClient["server.workspace.operatingChat"]) => (input: Endpoint22_1Input) =>
  raw["workspace.operatingChat.ensure"]({
    params: { workspaceID: input["workspaceID"], blockID: input["blockID"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint22_2Request = Parameters<RawClient["server.workspace.operatingChat"]["workspace.operatingChat.reset"]>[0]
type Endpoint22_2Input = {
  readonly workspaceID: Endpoint22_2Request["params"]["workspaceID"]
  readonly blockID: Endpoint22_2Request["params"]["blockID"]
  readonly expectedSessionID: Endpoint22_2Request["payload"]["expectedSessionID"]
  readonly expectedRevision: Endpoint22_2Request["payload"]["expectedRevision"]
}
const Endpoint22_2 = (raw: RawClient["server.workspace.operatingChat"]) => (input: Endpoint22_2Input) =>
  raw["workspace.operatingChat.reset"]({
    params: { workspaceID: input["workspaceID"], blockID: input["blockID"] },
    payload: { expectedSessionID: input["expectedSessionID"], expectedRevision: input["expectedRevision"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup22 = (raw: RawClient["server.workspace.operatingChat"]) => ({
  get: Endpoint22_0(raw),
  ensure: Endpoint22_1(raw),
  reset: Endpoint22_2(raw),
})

type Endpoint23_0Request = Parameters<RawClient["server.workspace.ctxpack"]["workspace.ctxpack.create"]>[0]
type Endpoint23_0Input = {
  readonly workspaceID: Endpoint23_0Request["params"]["workspaceID"]
  readonly title: Endpoint23_0Request["payload"]["title"]
  readonly keywords: Endpoint23_0Request["payload"]["keywords"]
  readonly tags?: Endpoint23_0Request["payload"]["tags"]
  readonly sensitivity: Endpoint23_0Request["payload"]["sensitivity"]
  readonly fragments: Endpoint23_0Request["payload"]["fragments"]
  readonly idempotencyKey: Endpoint23_0Request["payload"]["idempotencyKey"]
}
const Endpoint23_0 = (raw: RawClient["server.workspace.ctxpack"]) => (input: Endpoint23_0Input) =>
  raw["workspace.ctxpack.create"]({
    params: { workspaceID: input["workspaceID"] },
    payload: {
      title: input["title"],
      keywords: input["keywords"],
      tags: input["tags"],
      sensitivity: input["sensitivity"],
      fragments: input["fragments"],
      idempotencyKey: input["idempotencyKey"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint23_1Request = Parameters<RawClient["server.workspace.ctxpack"]["workspace.ctxpack.get"]>[0]
type Endpoint23_1Input = {
  readonly workspaceID: Endpoint23_1Request["params"]["workspaceID"]
  readonly ctxPackID: Endpoint23_1Request["params"]["ctxPackID"]
}
const Endpoint23_1 = (raw: RawClient["server.workspace.ctxpack"]) => (input: Endpoint23_1Input) =>
  raw["workspace.ctxpack.get"]({ params: { workspaceID: input["workspaceID"], ctxPackID: input["ctxPackID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint23_2Request = Parameters<RawClient["server.workspace.ctxpack"]["workspace.ctxpack.list"]>[0]
type Endpoint23_2Input = {
  readonly workspaceID: Endpoint23_2Request["params"]["workspaceID"]
  readonly query?: Endpoint23_2Request["query"]["query"]
  readonly keyword?: Endpoint23_2Request["query"]["keyword"]
  readonly sourceBlockID?: Endpoint23_2Request["query"]["sourceBlockID"]
  readonly sourceFunctionalityID?: Endpoint23_2Request["query"]["sourceFunctionalityID"]
  readonly sourceKind?: Endpoint23_2Request["query"]["sourceKind"]
  readonly sensitivity?: Endpoint23_2Request["query"]["sensitivity"]
  readonly createdAfter?: Endpoint23_2Request["query"]["createdAfter"]
  readonly createdBefore?: Endpoint23_2Request["query"]["createdBefore"]
  readonly includeDeleted?: Endpoint23_2Request["query"]["includeDeleted"]
  readonly pinnedOnly?: Endpoint23_2Request["query"]["pinnedOnly"]
  readonly sort?: Endpoint23_2Request["query"]["sort"]
  readonly cursor?: Endpoint23_2Request["query"]["cursor"]
  readonly limit?: Endpoint23_2Request["query"]["limit"]
}
const Endpoint23_2 = (raw: RawClient["server.workspace.ctxpack"]) => (input: Endpoint23_2Input) =>
  raw["workspace.ctxpack.list"]({
    params: { workspaceID: input["workspaceID"] },
    query: {
      query: input["query"],
      keyword: input["keyword"],
      sourceBlockID: input["sourceBlockID"],
      sourceFunctionalityID: input["sourceFunctionalityID"],
      sourceKind: input["sourceKind"],
      sensitivity: input["sensitivity"],
      createdAfter: input["createdAfter"],
      createdBefore: input["createdBefore"],
      includeDeleted: input["includeDeleted"],
      pinnedOnly: input["pinnedOnly"],
      sort: input["sort"],
      cursor: input["cursor"],
      limit: input["limit"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint23_3Request = Parameters<RawClient["server.workspace.ctxpack"]["workspace.ctxpack.pin"]>[0]
type Endpoint23_3Input = {
  readonly workspaceID: Endpoint23_3Request["params"]["workspaceID"]
  readonly ctxPackID: Endpoint23_3Request["params"]["ctxPackID"]
}
const Endpoint23_3 = (raw: RawClient["server.workspace.ctxpack"]) => (input: Endpoint23_3Input) =>
  raw["workspace.ctxpack.pin"]({ params: { workspaceID: input["workspaceID"], ctxPackID: input["ctxPackID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint23_4Request = Parameters<RawClient["server.workspace.ctxpack"]["workspace.ctxpack.unpin"]>[0]
type Endpoint23_4Input = {
  readonly workspaceID: Endpoint23_4Request["params"]["workspaceID"]
  readonly ctxPackID: Endpoint23_4Request["params"]["ctxPackID"]
}
const Endpoint23_4 = (raw: RawClient["server.workspace.ctxpack"]) => (input: Endpoint23_4Input) =>
  raw["workspace.ctxpack.unpin"]({ params: { workspaceID: input["workspaceID"], ctxPackID: input["ctxPackID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint23_5Request = Parameters<RawClient["server.workspace.ctxpack"]["workspace.ctxpack.patch"]>[0]
type Endpoint23_5Input = {
  readonly workspaceID: Endpoint23_5Request["params"]["workspaceID"]
  readonly ctxPackID: Endpoint23_5Request["params"]["ctxPackID"]
  readonly expectedRevision: Endpoint23_5Request["payload"]["expectedRevision"]
  readonly patch: Endpoint23_5Request["payload"]["patch"]
  readonly idempotencyKey: Endpoint23_5Request["payload"]["idempotencyKey"]
}
const Endpoint23_5 = (raw: RawClient["server.workspace.ctxpack"]) => (input: Endpoint23_5Input) =>
  raw["workspace.ctxpack.patch"]({
    params: { workspaceID: input["workspaceID"], ctxPackID: input["ctxPackID"] },
    payload: {
      expectedRevision: input["expectedRevision"],
      patch: input["patch"],
      idempotencyKey: input["idempotencyKey"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint23_6Request = Parameters<RawClient["server.workspace.ctxpack"]["workspace.ctxpack.remove"]>[0]
type Endpoint23_6Input = {
  readonly workspaceID: Endpoint23_6Request["params"]["workspaceID"]
  readonly ctxPackID: Endpoint23_6Request["params"]["ctxPackID"]
  readonly expectedRevision: Endpoint23_6Request["payload"]["expectedRevision"]
}
const Endpoint23_6 = (raw: RawClient["server.workspace.ctxpack"]) => (input: Endpoint23_6Input) =>
  raw["workspace.ctxpack.remove"]({
    params: { workspaceID: input["workspaceID"], ctxPackID: input["ctxPackID"] },
    payload: { expectedRevision: input["expectedRevision"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint23_7Request = Parameters<RawClient["server.workspace.ctxpack"]["workspace.ctxpack.restore"]>[0]
type Endpoint23_7Input = {
  readonly workspaceID: Endpoint23_7Request["params"]["workspaceID"]
  readonly ctxPackID: Endpoint23_7Request["params"]["ctxPackID"]
  readonly expectedRevision: Endpoint23_7Request["payload"]["expectedRevision"]
}
const Endpoint23_7 = (raw: RawClient["server.workspace.ctxpack"]) => (input: Endpoint23_7Input) =>
  raw["workspace.ctxpack.restore"]({
    params: { workspaceID: input["workspaceID"], ctxPackID: input["ctxPackID"] },
    payload: { expectedRevision: input["expectedRevision"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint23_8Request = Parameters<RawClient["server.workspace.ctxpack"]["workspace.ctxpack.materialize"]>[0]
type Endpoint23_8Input = {
  readonly workspaceID: Endpoint23_8Request["params"]["workspaceID"]
  readonly ctxPackID: Endpoint23_8Request["params"]["ctxPackID"]
  readonly expectedContentHash: Endpoint23_8Request["payload"]["expectedContentHash"]
  readonly targetInstanceID: Endpoint23_8Request["payload"]["targetInstanceID"]
  readonly targetFunctionalityID: Endpoint23_8Request["payload"]["targetFunctionalityID"]
}
const Endpoint23_8 = (raw: RawClient["server.workspace.ctxpack"]) => (input: Endpoint23_8Input) =>
  raw["workspace.ctxpack.materialize"]({
    params: { workspaceID: input["workspaceID"], ctxPackID: input["ctxPackID"] },
    payload: {
      expectedContentHash: input["expectedContentHash"],
      targetInstanceID: input["targetInstanceID"],
      targetFunctionalityID: input["targetFunctionalityID"],
    },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup23 = (raw: RawClient["server.workspace.ctxpack"]) => ({
  create: Endpoint23_0(raw),
  get: Endpoint23_1(raw),
  list: Endpoint23_2(raw),
  pin: Endpoint23_3(raw),
  unpin: Endpoint23_4(raw),
  patch: Endpoint23_5(raw),
  remove: Endpoint23_6(raw),
  restore: Endpoint23_7(raw),
  materialize: Endpoint23_8(raw),
})

const adaptClient = (raw: RawClient) => ({
  health: adaptGroup0(raw["server.health"]),
  location: adaptGroup1(raw["server.location"]),
  agents: adaptGroup2(raw["server.agent"]),
  sessions: adaptGroup3(raw["server.session"]),
  messages: adaptGroup4(raw["server.message"]),
  models: adaptGroup5(raw["server.model"]),
  providers: adaptGroup6(raw["server.provider"]),
  integrations: adaptGroup7(raw["server.integration"]),
  credentials: adaptGroup8(raw["server.credential"]),
  permissions: adaptGroup9(raw["server.permission"]),
  files: adaptGroup10(raw["server.fs"]),
  commands: adaptGroup11(raw["server.command"]),
  skills: adaptGroup12(raw["server.skill"]),
  events: adaptGroup13(raw["server.event"]),
  ptys: adaptGroup14(raw["server.pty"]),
  questions: adaptGroup15(raw["server.question"]),
  references: adaptGroup16(raw["server.reference"]),
  projectCopies: adaptGroup17(raw["server.projectCopy"]),
  "server.workspace": adaptGroup18(raw["server.workspace"]),
  "server.workspace.masterAgent": adaptGroup19(raw["server.workspace.masterAgent"]),
  "server.workspace.chatRelay": adaptGroup20(raw["server.workspace.chatRelay"]),
  chatProxy: adaptGroup21(raw["server.chatProxy"]),
  "server.workspace.operatingChat": adaptGroup22(raw["server.workspace.operatingChat"]),
  "server.workspace.ctxpack": adaptGroup23(raw["server.workspace.ctxpack"]),
})

export const make = (options?: { readonly baseUrl?: URL | string }) =>
  HttpApiClient.make(ClientApi, options).pipe(Effect.map(adaptClient))
